### PR TITLE
Gh529 visual document classifier v2 add train ability

### PR DESCRIPTION
**Pull request by albertoandreottiATgmail**

### CODE REVIEW

**Review by albertoandreottiATgmail — COMMENTED** [review]
All that you have in the preprocessing notebook, until you do,

df.show(5)

put it into a reader. Something like,

df = DatasetReader.read_rvl_cdip("./path_to_rvl_cdip")

**Comment by albertoandreottiATgmail** [comment]
also, it seems you have an error when lifting the vocabulary file,

invalid literal for int() with base 10: '' ##,,29623
 ['##', '', '29623']

something is not right there. Look,

occasions,6642
##,,29623
##ffy,16329

it means you're not loading the token for the comma at the end of a word! that's an important one.
Handle this properly please @xyutech

**Comment by albertoandreottiATgmail** [comment]
also remove your name from the paths, use relative paths instead,



file:/home/alexan... 

should go to,

"./datasets/rvl_cdip/whatever"

We need to share this with customers.

**Comment by xyutech** [comment]
> also remove your name from the paths, use relative paths instead
I use those paths through the code but spark when display dataframe shows full path. I hide such columns.

**Comment by xyutech** [comment]
Regarding Datasets - I propose to implement it in separate ticket.

**Comment by xyutech** [comment]
@albertoandreottiATgmail Please check recent update. Seems to be ready for merging.

**Pull request merged**
